# **1. buat variabel skalar x dan simpan suatu nilai skalar**

In [ ]:
# buat variabel skalar x dan simpan suatu nilai skalar
x = 2
x

In [ ]:
# tampilkan tipe data dari x
type (x)

In [ ]:
# buat variabel skalar y dan simpan suatu nilai skalar
y = 20
y

In [ ]:
# jumlahkan x+y
py_sum = x + y
py_sum

In [ ]:
# buat variabel bernama x_float dan simpan suatu nilai desimal
x_float = 25.5
x_float

In [ ]:
# jumlahkan x_float dengan y
float_sum = x_float + y
float_sum

In [ ]:
# tampilkan tipe data dari x_float
type(float_sum)

2. **Lakukan tahapan pada soal 1 dengan menggunakan Tensorflow**


In [ ]:
import tensorflow as tf

In [ ]:
# buat variabel tensorflow dan simpan suatu nilai tensorflow
x_tf = tf.Variable(20, dtype=tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=20>

In [ ]:
# Menampilkan tipe data x
x_tf.shape

TensorShape([])

In [ ]:
# buat variabel tensorflow dan simpan suatu nilai tensorflow
y_tf = tf.Variable(25, dtype=tf.int16)
y_tf

In [ ]:
# tampilkan tipe data dari y
y_tf.shape

In [ ]:
# Jumlahkan x+y
x_tf + y_tf

In [ ]:
# buat variabel float
x_float = tf.Variable(2.5, dtype=tf.float16)
x_float

In [ ]:
# Jumlahkan x float
x_float + tf.cast(y_tf, dtype=tf.float16)

In [ ]:
# Menampilkan Tipe data dari x_float
type(x_float.numpy())

3. Melakukan tahapan pada soal 1 dengan menggunakan pytorch

In [ ]:
import torch

In [ ]:
#Membuat tipe data x
x_pt = torch.tensor(20) # type specification optional, e.g.: dtype=torch.float16
x_pt

tensor(20)

In [ ]:
# Menampilkan tipe data x
x_pt.shape

torch.Size([])

In [ ]:
#Membuat tipe data y
y_pt = torch.tensor(2) # type specification optional, e.g.: dtype=torch.float16
y_pt

tensor(2)

In [ ]:
# Menampilkan tipe data y
y_pt.shape

torch.Size([])

In [ ]:
# Menjumlahkan x dan y
x_pt + y_pt

tensor(22)

Vector and Vector Transposition

In [ ]:
import numpy as np

In [ ]:
# Membuat Vector ukuran 3x1
x = np.array([20, 2, 55]) # type argument is optional, e.g.: dtype=np.float16
x

array([20,  2, 55])

In [ ]:
# Hitung panjang vector x
len(x)

2

In [ ]:
# Menampilkan ukuran vector
x.shape

(2,)

In [ ]:
# Menampilkan tipe data vector x
type(x)

numpy.ndarray

In [ ]:
# Akses Elemen Pertama
x[0]

np.int64(20)

In [ ]:
# Menampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [ ]:
# 2. Melakukan Transpose pada vector x dan simpan variabel x_t
x_t = x.T
x_t

array([20,  2, 55])

In [ ]:
# Menampilkan ukuran vector x_t
x_t.shape

In [ ]:
# Melakukan Transpose pada vector y dan simpan pada variabel y_t
y = np.array([[20, 2, 55]])
y

y_t = y.T
y_t

array([[20],
       [ 2],
       [55]])

In [ ]:
# Menampilkan ukuran vector y_t
y_t.shape

(3, 1)

3. melakukan soal no 2 menggunakan pytorch dan tensor flow

In [ ]:
import torch
import tensorflow as tf


In [ ]:
# Menampilkan vector x
x_pt = torch.tensor([20, 2, 55])
x_pt

tensor([20,  2, 55])

In [ ]:
# Melakukan Transpose
x_pt = x.T
x_pt

array([20,  2, 55])

In [ ]:
# Type dan ukuran dari vector
x_tf = tf.Variable([20, 2, 55])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([20,  2, 55], dtype=int32)>

In [ ]:
# Menampilkan vector y
y_pt = torch.tensor([20, 2, 55])
y_pt

tensor([20,  2, 55])

In [ ]:
# Melakukan Transpose
y_pt = y.T
y_pt

array([[20],
       [ 2],
       [55]])

In [ ]:
# Type dan ukuran dari vector
y_tf = tf.Variable([20, 2, 55])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([20,  2, 55], dtype=int32)>

Norms and Unit Vectors

In [ ]:
# Membuat Vector x dengan ukuran 3x1
x = np.array([20, 2, 55])
x

array([20,  2, 55])

In [ ]:
# Menghitung L2 Norm dari vector x
(20**2 + 2**2 + 55**2)**(1/2)

58.557663887829406

In [ ]:
np.linalg.norm(x)

np.float64(58.557663887829406)

In [ ]:
# 2. buat vector v dengan elemen (3,4)
#hitung nilai L2 norm dari vector v
#tampilkan unit vector dari vector v
#hitung panjang unit vector dari vector v

# Membuat vektor
v = np.array([3, 4])

# Menghitung panjang (norma L2)
norm = np.linalg.norm(v)

# Menghitung unit vector
unit_v = v / norm

print("Vektor asli:", v)
print("Panjang vektor:", norm)
print("Unit vector:", unit_v)
print("Panjang unit vector:", np.linalg.norm(unit_v))

Vektor asli: [3 4]
Panjang vektor: 5.0
Unit vector: [0.6 0.8]
Panjang unit vector: 1.0


Basis, Orthogonal and Orthonormal Vectors

In [ ]:
import numpy as np


In [ ]:
# buat vector i dengan elemen (1,0) dan vector j dengan elemen (0,1)
i = np.array([1, 0])
i

array([1, 0])

In [ ]:
j = np.array([0, 1])
j

array([0, 1])

In [ ]:
# Membuktikan bahwa vector i dan j orthogonal
np.dot(i, j)
print (np.dot (i, j))

# Jika hasilnya adalah 0 maka nilainya orthogonal

0
Vector i dan j adalah orthogonal


In [ ]:
# buat vector v dengan elemen (1,2) dan vector w dengan elemen (2,-1)
v = np.array([1, 2])
v

array([1, 2])

In [ ]:
w = np.array([2, -1])
w

array([ 2, -1])

In [ ]:
# Membuktikkan apakah vector v dan w orthogonal
np.dot(v, w)
print (np.dot (v, w))
# # Jika hasilnya adalah 0 maka nilainya orthogonal

0
Vector v dan w adalah orthogonal


Matrix Tensor

In [ ]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[25, 55], [6, 61], [0, 2]])
X

array([[25, 55],
       [ 6, 61],
       [ 0,  2]])

In [ ]:
# Menampilkan ukuran matrix
X.shape

(3, 2)

In [ ]:
# Menampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([25,  6,  0])

In [ ]:
# Menampilkan Seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([ 6, 61])

In [ ]:
# Menggunakan pytorch
import torch

In [ ]:
# Membuat matrix ukuran 2x3
X_pt = torch.tensor([[25, 55], [6, 61], [0, 2]])
X_pt

tensor([[25, 55],
        [ 6, 61],
        [ 0,  2]])

In [ ]:
# Menampilkan ukuran
X_pt.shape

torch.Size([3, 2])

In [ ]:
import torch

# Menampilkan seluruh elemen dari kolom pertama dari matrix X
X_pt[:,0]

tensor([25,  6,  0])

In [ ]:
# Menampilkan Seluruh elemen dari baris kedua dari matrix X
X_pt[1,:]

tensor([ 6, 61])

In [ ]:
# Tensor Flow
import tensorflow as tf

In [ ]:
# Membuat matrix X berukuran 2x3 menggunakan numpy
X_tf = tf.Variable([[25, 55], [6, 61], [0, 2]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25, 55],
       [ 6, 61],
       [ 0,  2]], dtype=int32)>

In [ ]:
# Menampilkan Ukuran

tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [ ]:
# Menampilkan seluruh elemen dari kolom pertama dari matrix X
X_tf[:,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25,  6,  0], dtype=int32)>

In [ ]:
# Menampilkan Seluruh elemen dari baris kedua dari matrix X
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 6, 61], dtype=int32)>

GENERIC TENSOR NATION

In [ ]:
# jelaskan tentang perintah ini images_pt = torch.zeros([32, 28, 28, 3])

import torch
images_pt = torch.zeros([32, 28, 28, 3])
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

Exercise  on Algebra Data Structures

In [ ]:
# Transpose dari kolom (25,2,-3,-23)
XT = np.array([[25], [2], [-3], [-23]])
XT



array([[ 25],
       [  2],
       [ -3],
       [-23]])

In [ ]:
XT_T = XT.T
XT_T

array([[ 25,   2,  -3, -23]])